
export const PROPOSE_PROJECT = "PROPOSE_PROJECT"

export const ACCESS_OFFERED_PROJECT_LIST = "ACCESS_OFFERED_PROJECT_LIST"

export const ACCESS_OFFERED_PROJECT = "ACCESS_OFFERED_PROJECT"

export const OFFER_SERVICE_TO_PROJECT = "OFFER_SERVICE_TO_PROJECT"

export const ACCESS_INTERESTED_DEV_LIST = "ACCESS_INTERESTED_DEV_LIST"

export const SELECT_INTERESTED_DEV = "SELECT_INTERESTED_DEV"
